{% set name = "onnxmltools" %}
{% set version = "1.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/onnx/onnxmltools.git
  git_rev: {{ version }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy {{ numpy }}
    - onnx {{ onnx }}
    - skl2onnx
    - onnxruntime

test:
  imports:
    - onnxmltools

about:
  home: https://github.com/onnx/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
